# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b91d81ad937f922e55ecafb1489e5a06ce5f33a9d853935dd2ef644cd2e78879cd3b3a3b8e411b64c0e807946367860b921f9a5527e46cd841a95b30362520

test:
  secret_key_base: 16f6502ab1a52132a4dfded7bbeaef5a8b96f51bebc830c566df447faf40ed8008d6b5f65d45af88e256b126d79b76986cb47f740b87986886105b3fcf3b1b6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
